export const TRACKS = {
  math:{c:'var(--math)', label:'Mathematiques'},
  ml:{c:'var(--ml)', label:'Machine / Deep Learning'},
  graph:{c:'var(--graph)', label:'Machine Learning sur graphe'},
  algo:{c:'var(--algo)', label:'Algorithmique'},
  data:{c:'var(--data)', label:'Donnees et mise en production'},
  proj:{c:'var(--proj)', label:'Projets'}
}

// col = progression (gauche->droite), row = position verticale
export const NODES = [
  // ---- MATH ----
  {id:'m1', tk:'math', col:0, row:0, t:'M1 · Algebre lineaire',
   n:['vecteur, scalaire','produit scalaire, norme','matrice, produit matriciel','determinant, rang','systemes lineaires','valeurs et vecteurs propres','diagonalisation','SVD'], p:[]},
  {id:'m2', tk:'math', col:1, row:0, t:'M2 · Calcul differentiel',
   n:['limite, continuite','derivee','derivee partielle','gradient','matrice jacobienne','hessienne','regle de la chaine','developpement de Taylor'], p:['m1']},
  {id:'m4', tk:'math', col:2, row:0, t:'M4 · Optimisation convexe',
   n:['ensembles et fonctions convexes','sous-differentiel','descente de gradient','conditions du 2e ordre','KKT, dualite de Lagrange','operateur proximal','gradient implicite','primal-dual'], p:['m2']},
  {id:'m3', tk:'math', col:2, row:1, t:'M3 · Probabilites et stats',
   n:['variable aleatoire','esperance, variance','covariance, correlation','independance','probabilite conditionnelle','theoreme de Bayes','lois usuelles','estimation, max de vraisemblance','ACP, LDA, tests'], p:['m1','m2']},
  {id:'m5', tk:'math', col:3, row:1, t:'M5 · Processus stochastiques',
   n:['chaines de Markov','processus de Poisson','mouvement brownien','integrale d Ito','equations differentielles stochastiques','MCMC, Monte-Carlo','processus de diffusion'], p:['m3']},
  {id:'m7', tk:'math', col:3, row:2, t:'M7 · Prediction conforme',
   n:['quantification d incertitude','regression quantile','split conformal prediction','conformal quantile regression','fonction de score','couverture, echangeabilite'], p:['m3']},
  {id:'m6', tk:'math', col:4, row:1, t:'M6 · Series temporelles',
   n:['stationnarite','ACF, PACF','bruit blanc','AR, MA, ARMA','ARIMA, SARIMA','decomposition tendance/saison','VAR multivarie','FPCA fonctionnel'], p:['m3','m5']},

  // ---- ML core ----
  {id:'ml1', tk:'ml', col:1, row:4, t:'ML1 · Apprendre des donnees',
   n:['X, Y, prediction','supervise vs non supervise','classification vs regression','generalisation','risque empirique vs reel','compromis biais-variance','train / validation / test','sur- et sous-apprentissage','fuite de donnees'], p:['m1']},
  {id:'ml2', tk:'ml', col:2, row:4, t:'ML2 · Evaluation, desequilibre',
   n:['matrice de confusion','precision, rappel, F1','specificite','courbe ROC, AUC','courbe PR, AUPRC','baseline naif','classes desequilibrees','reechantillonnage'], p:['ml1']},
  {id:'ml3', tk:'ml', col:3, row:4, t:'ML3 · Modeles classiques',
   n:['regression lineaire','regression logistique, sigmoide','entropie croisee','k plus proches voisins','arbres de decision','forets aleatoires','gradient boosting','k-means','regularisation L1 / L2','selection de variables'], p:['ml1','ml2','m1','m2','m3']},
  {id:'dl', tk:'ml', col:4, row:4, t:'DL · Reseaux de neurones',
   n:['neurone, perceptron','perceptron multicouche','fonctions d activation','propagation avant','retropropagation','SGD, momentum, Adam','initialisation','batch norm, dropout','embeddings, representation'], p:['ml3','m2','m4']},
  {id:'ad', tk:'ml', col:5, row:2, t:'AD · Programmation differentiable',
   n:['derivation numerique vs symbolique','graphe de calcul','mode forward (JVP)','mode reverse (VJP)','regle de la chaine automatisee','tenseurs et autograd','nn.Module','optimisation pour le deep learning'], p:['dl','m4']},
  {id:'cnn', tk:'ml', col:5, row:4, t:'DL · CNN / RNN / Transformers',
   n:['convolution, pooling (CNN)','RNN, LSTM','mecanisme d attention','Transformers','sequences et images'], p:['dl']},
  {id:'rl', tk:'ml', col:5, row:5, t:'RL · Apprentissage par renforcement',
   n:['processus de decision markovien','etat, action, recompense','politique, fonction de valeur','equation de Bellman','exploration-exploitation','Q-learning, DQN','policy gradient','acteur-critique, PPO','reward design'], p:['dl','m3','m5']},
  {id:'ml4', tk:'ml', col:4, row:5, t:'ML4 · Non supervise et anomalies',
   n:['clustering, k-means, DBSCAN','reduction de dimension pour l anomalie','IsolationForest','OneClassSVM','Local Outlier Factor','score d anomalie et seuillage','evaluation sans etiquettes'], p:['ml3','m3']},
  {id:'rec', tk:'ml', col:4, row:6, t:'ML5 · Systemes de recommandation',
   n:['matrice utilisateurs x items','filtrage base contenu','filtrage collaboratif','KNN user-based et item-based','factorisation matricielle, SVD','demarrage a froid','RMSE, precision@k, rappel@k'], p:['ml3','m1']},
  {id:'gen', tk:'ml', col:5, row:6, t:'DL · Modeles generatifs',
   n:['auto-encodeur','VAE, espace latent','GAN, generateur et discriminateur','modeles de diffusion','bruitage puis debruitage','echantillonnage'], p:['dl','m5']},
  {id:'cv', tk:'ml', col:6, row:2, t:'CV · Vision par ordinateur',
   n:['descripteurs classiques, Harris','template matching','appariement de patches','detection d objets','segmentation semantique','augmentation de donnees','imagerie medicale 3D, patches'], p:['cnn']},
  {id:'nlp', tk:'ml', col:6, row:4, t:'NLP · Texte et representations',
   n:['tokenisation, lemmatisation','sac de mots, TF-IDF','patterns et regles (spaCy)','reconnaissance d entites nommees','word embeddings','classification de texte','RNN puis Transformers pour le texte'], p:['cnn','ml3']},
  {id:'llm', tk:'ml', col:7, row:4, t:'NLP · LLM et agents',
   n:['modele de langue pre-entraine','fine-tuning (GPT-2)','prompting, sorties JSON structurees','modeles locaux (Ollama)','agent: memoire, outils, etat','orchestration multi-agents'], p:['nlp']},
  {id:'xai', tk:'ml', col:6, row:5, t:'XAI · Explicabilite',
   n:['importance de variables, permutation','SHAP, valeurs de Shapley','LIME','explication locale vs globale','cartes de saillance, GradCAM','TCAV, concepts','ProtoPNet, prototypes','equite algorithmique'], p:['ml3','dl']},
  {id:'advml', tk:'ml', col:7, row:5, t:'SEC · Robustesse et adversarial',
   n:['surface d attaque d un modele','boite blanche vs boite noire','FGSM, PGD','empoisonnement de donnees','adversarial training','detection d exemples adversariaux','systemes cyber-physiques'], p:['dl','ml2','ml4']},

  // ---- ML SUR GRAPHE (sous-piste dediee) ----
  {id:'gth', tk:'graph', col:3, row:9, t:'G1 · Fondations de graphes',
   n:['matrice d adjacence, degre','laplacien de graphe','marches aleatoires, RWR','mesures de centralite','homophilie et voisinage','prediction de liens sans ML'], p:['m1','g_graphs']},
  {id:'gemb', tk:'graph', col:4, row:9, t:'G2 · Embeddings de noeuds',
   n:['DeepWalk','Node2Vec','random walk with restart','factorisation matricielle','features de noeuds','du MLP au GNN vanilla'], p:['gth','ml1']},
  {id:'gnn', tk:'graph', col:5, row:9, t:'G3 · GNN coeur (GCN, GAT)',
   n:['passage de messages','GNN vanilla et ses limites','GCN, normalisation des features','classification et regression de noeuds','GAT, attention sur les voisins','sur-lissage'], p:['dl','gemb','m1']},
  {id:'gnn2', tk:'graph', col:6, row:6, t:'G4 · GNN avances, expressivite',
   n:['GraphSAGE, echantillonnage de voisinage','passage a l echelle','GIN','expressivite d un GNN','test de Weisfeiler-Lehman'], p:['gnn']},
  {id:'gtask', tk:'graph', col:6, row:10, t:'G5 · Taches sur graphe',
   n:['classification de noeuds','prediction de liens (SEAL, sous-graphes)','classification de graphes entiers','pooling de graphe'], p:['gnn']},
  {id:'gtemp', tk:'graph', col:7, row:9, t:'G6 · Graphes temporels et DGT',
   n:['GNN temporels','graphes dynamiques, multigraphes','Differential Graph Transformer','application trafic et marche'], p:['gnn2','cnn','m6']},

  // ---- ALGO ----
  {id:'a_cx', tk:'algo', col:0, row:13, t:'A1 · Complexite',
   n:['comptage d operations','notation grand O','complexite spatiale','couts caches en Python'], p:[]},
  {id:'a_ds', tk:'algo', col:1, row:13, t:'A2 · Structures de donnees',
   n:['listes, tableaux','dictionnaires, ensembles','piles, files','deque'], p:['a_cx']},
  {id:'a_bits', tk:'algo', col:1, row:14, t:'A · Manipulation de bits',
   n:['operateurs binaires','masques','decalages','astuces de comptage'], p:['a_cx']},
  {id:'a_mod', tk:'algo', col:1, row:15, t:'A · Arithmetique modulaire',
   n:['modulo, congruences','PGCD, Bezout','exponentiation rapide','inverse modulaire'], p:['a_cx']},
  {id:'a_rec', tk:'algo', col:2, row:13, t:'A3 · Recursivite',
   n:['cas de base et recurrence','pile d appels','diviser pour regner','backtracking'], p:['a_ds']},
  {id:'a_srt', tk:'algo', col:2, row:14, t:'A4 · Tri et recherche',
   n:['tris classiques','recherche dichotomique','invariants'], p:['a_cx','a_ds']},
  {id:'a_hash', tk:'algo', col:2, row:15, t:'A · Hachage',
   n:['tables de hachage','comptage, frequences','memoisation'], p:['a_ds']},
  {id:'g_graphs', tk:'algo', col:3, row:13, t:'A6 · Graphes (algo)',
   n:['representation','parcours BFS, DFS','plus courts chemins, Dijkstra','composantes connexes','detection de cycles'], p:['a_rec']},
  {id:'a_2p', tk:'algo', col:3, row:14, t:'A5 · Deux pointeurs',
   n:['deux pointeurs','fenetre glissante','conditions de deplacement'], p:['a_srt']},
  {id:'a_gr', tk:'algo', col:3, row:15, t:'A · Glouton',
   n:['choix local optimal','preuve d optimalite','contre-exemples'], p:['a_srt']},
  {id:'a_dp', tk:'algo', col:4, row:14, t:'A7 · Programmation dynamique',
   n:['sous-problemes','memoisation','tabulation','equation de recurrence'], p:['a_rec','a_hash']},

  // ---- DONNEES ET MISE EN PRODUCTION ----
  {id:'d1', tk:'data', col:0, row:16, t:'D1 · EDA et visualisation',
   n:['types de variables','valeurs manquantes, doublons','distributions, valeurs aberrantes','correlations','ingenierie de variables','grammaire graphique','projection PCA / t-SNE pour explorer','raconter un jeu de donnees'], p:[]},
  {id:'d2', tk:'data', col:2, row:16, t:'D3 · Big data et calcul distribue',
   n:['Spark, PySpark','RDD et DataFrame','evaluation paresseuse','partitionnement, shuffle','MLlib','nettoyage a grande echelle'], p:['d1','ml1']},
  {id:'mlops', tk:'data', col:4, row:16, t:'D4 · MLOps et mise en production',
   n:['versionnage de donnees (DVC)','pipeline reproductible','suivi d experiences (MLflow)','registre de modeles, artefacts','API de prediction (FastAPI)','frontend de demonstration','conteneurisation du service (Docker)','re-entrainement, derive, monitoring'], p:['ml3','d1']},

  // ---- PROJETS DE COURS : maths et stats (rangee sous la bande math) ----
  {id:'pj_acp', tk:'proj', col:0, row:3, t:'P · ACP Iris et temperatures (PRBS)',
   n:['matrice de covariance','valeurs et vecteurs propres','variance expliquee','projection et lecture des axes'], p:['m1']},
  {id:'pj_gd', tk:'proj', col:1, row:3, t:'P · Descente de gradient (OCVX)',
   n:['implementation de la descente','choix du pas, convergence','visualisation des trajectoires'], p:['m2']},
  {id:'pj_lda', tk:'proj', col:2, row:3, t:'P · ACP et LDA en R (PRBS)',
   n:['analyse discriminante lineaire','donnees medicales','R et visualisation statistique'], p:['m3']},
  {id:'pj_prox', tk:'proj', col:3, row:3, t:'P · Operateur proximal (OCVX2)',
   n:['operateur proximal','gradient implicite','algorithmes proximaux','TP note'], p:['m4']},
  {id:'pj_fin', tk:'proj', col:4, row:3, t:'P · Modelisation financiere en R (Stochastique)',
   n:['series financieres','simulation de trajectoires','estimation de parametres'], p:['m5']},
  {id:'pj_conf', tk:'proj', col:5, row:3, t:'P · Prediction conforme (Stochastique)',
   n:['garanties de couverture','regression quantile conforme','jeu de calibration','deja rendu'], p:['m7']},
  {id:'pj_arima', tk:'proj', col:6, row:3, t:'P · ARIMA sur series reelles (TSA)',
   n:['tests ADF et KPSS','ACF et PACF','choix d ordre (p,d,q)','prevision et analyse des residus'], p:['m6']},
  {id:'pj_diff', tk:'proj', col:7, row:3, t:'P · Pixel art par diffusion (Stochastique)',
   n:['mouvement brownien','processus de bruitage','debruitage appris','generation d images'], p:['m5','gen']},

  // ---- PROJETS DE COURS : machine learning (rangees sous la bande ML) ----
  {id:'pj_mnist', tk:'proj', col:1, row:7, t:'P · Projet end-to-end MNIST (MACH)',
   n:['cycle complet d un projet ML','70k chiffres manuscrits','protocole d evaluation'], p:['ml1','ml2']},
  {id:'pj_mnistc', tk:'proj', col:3, row:7, t:'P · Classification MNIST (MACH)',
   n:['SVM','arbres et forets','gradient boosting','comparaison de modeles'], p:['ml3']},
  {id:'pj_rec', tk:'proj', col:4, row:7, t:'P · Recommandation MovieLens (RecSys)',
   n:['MovieLens 100K et 1M','filtrage base contenu','KNN user et item','SVD, RMSE, rappel@k'], p:['rec']},
  {id:'pj_gal', tk:'proj', col:5, row:7, t:'P · Classification de galaxies (RDN)',
   n:['spirales, elliptiques, irregulieres','CNN sur images astro','augmentation de donnees'], p:['cnn']},
  {id:'pj_gen', tk:'proj', col:6, row:7, t:'P · TP modeles generatifs (HDL)',
   n:['auto-encodeur','VAE','GAN','qualite de generation'], p:['gen']},
  {id:'pj_gpt', tk:'proj', col:7, row:7, t:'P · Fine-tuning GPT-2 (HDL)',
   n:['corpus Le Petit Prince','tokenizer et contexte','fine-tuning','generation de texte'], p:['llm']},
  {id:'pj_xaitab', tk:'proj', col:8, row:7, t:'P · XAI, SHAP et LIME (XAI)',
   n:['UCI Adult, revenus','attrition RH','defaut de paiement','local vs global, fairness','explication d un modele image'], p:['xai']},
  {id:'pj_sae', tk:'proj', col:9, row:7, t:'P · SAE course auto, autodiff et MPC (DIFFACT)',
   n:['moteur d autodiff en NumPy pur (Tensor, backward)','broadcasting et regle de la chaine','Linear, MLP, SGD, Adam recodes','modele bicyclette differentiable','MPC : horizon optimise par descente de gradient','ML-MPC : correction apprise du modele nominal','collecte de donnees puis entrainement','conformite verifiee contre PyTorch'], p:['ad','dl','m4']},
  {id:'pj_rl', tk:'proj', col:4, row:8, t:'P · Q-Learning, DQN, Policy Gradient (RL)',
   n:['bandits multibras','Q-learning tabulaire','DQN','policy gradient','devoir maison'], p:['rl']},
  {id:'pj_pytorch', tk:'proj', col:5, row:8, t:'P · Piscine PyTorch (DIFFACT)',
   n:['step 1 : tenseurs et autograd','step 2 : couches et regression','step 3 : CNN','step 4 : architectures avancees'], p:['ad','dl']},
  {id:'pj_interp', tk:'proj', col:6, row:8, t:'P · Interpretabilite profonde (HDL)',
   n:['cartes de saillance, GradCAM','TCAV, vecteurs de concepts','ProtoPNet, prototypes'], p:['xai']},
  {id:'pj_swat', tk:'proj', col:8, row:8, t:'P · CYBERML SWaT (ML-SEC)',
   n:['systeme cyber-physique de traitement d eau','3 modeles non supervises','3 modeles supervises','MCC, balanced accuracy, AUPRC'], p:['ml4','advml','ml2']},
  {id:'pj_adv', tk:'proj', col:9, row:8, t:'P · Labs attaques adversariales (ML-SEC)',
   n:['FGSM','PGD','boite blanche et boite noire','defenses et detection'], p:['advml']},

  // ---- PROJETS DE COURS : graphes (rangee sous la bande graphe) ----
  {id:'pj_rwr', tk:'proj', col:4, row:12, t:'P · Classification de noeuds et RWR (ML-GRAPH)',
   n:['representation de graphes','random walk with restart','features de noeuds'], p:['gemb']},
  {id:'pj_gcn', tk:'proj', col:5, row:12, t:'P · GCN et GAT en PyTorch Geometric (GNN)',
   n:['message passing','GCN','attention GAT','datasets de reference'], p:['gnn']},
  {id:'pj_gtask', tk:'proj', col:6, row:12, t:'P · Prediction de liens et de graphes (ML-GRAPH)',
   n:['prediction de liens','classification de graphes entiers','pooling de graphe'], p:['gtask']},
  {id:'pj_dgt', tk:'proj', col:7, row:12, t:'P · Stock Market Forecasting DGT (GNN)',
   n:['graphe dynamique inter-actifs','Differential Graph Transformer','prevision boursiere'], p:['gtemp']},

  // ---- PROJETS DE COURS : algo et donnees ----
  {id:'pj_eda', tk:'proj', col:0, row:17, t:'P · EDA transactions sequentielles (EDA)',
   n:['exploration et nettoyage','valeurs manquantes','distributions et correlations'], p:['d1']},
  {id:'pj_us', tk:'proj', col:2, row:17, t:'P · US Accidents sur Spark (BDA)',
   n:['50 colonnes, donnees massives','nettoyage PySpark','detection d anomalies','prediction de gravite'], p:['d2']},

  // ---- PROJETS CIBLES ----
  {id:'p_fraud', tk:'proj', col:5, row:11, t:'P · Fraude (tabulaire v0)',
   n:['pipeline tabulaire','gestion du desequilibre','evaluation rigoureuse','baseline vs modele'], p:['ml3','ml2','ml4','d1']},
  {id:'p_nlp', tk:'proj', col:8, row:2, t:'P · Filtre documentaire NLP',
   n:['nettoyage de texte','representation, embeddings','classification de documents'], p:['nlp']},
  {id:'p_llm', tk:'proj', col:8, row:1, t:'P · LLM Society (agents)',
   n:['LLM et prompting','orchestration multi-agents','LangChain / LangGraph','memoire, outils'], p:['llm']},
  {id:'p_fgraph', tk:'proj', col:8, row:9, t:'P · Fraude sur graphe (GNN)',
   n:['graphe de transactions','GraphSAGE / GAT','desequilibre sur graphe','explicabilite GNN (GNNExplainer)'], p:['p_fraud','gtask','gnn2','xai']},
  {id:'p_trader', tk:'proj', col:9, row:10, t:'P · Neuro-Graph Trader',
   n:['graphe dynamique de marche','Differential Graph Transformer','agent RL (PPO)','sentiment de marche (FinBERT)','non-stationnarite','fuite temporelle, backtest honnete'], p:['p_fgraph','rl','gtemp','m5','m6','nlp']},
]

// livrables restes en fiche : ceux qui n ont pas de carte projet dediee sur le plan
export const PROJ = {
  cv:[{n:'Twin It, vision (MLRF)',w:'template matching, Harris, descripteurs, matching'}],
  nlp:[{n:'Extraction de competences spaCy (NLP)',w:'patterns, NER et lemmatisation sur des CVs'}],
  pj_sae:[{n:'py-allumette-2526 (Desktop/maeva)',w:'student/autodiff, student/ml, student/mpc a implementer ; pytest --impl student'}],
  mlops:[{n:'Pipeline MLOps MNIST (ML-OPS)',w:'DVC, MLflow, FastAPI, Streamlit et Docker de bout en bout'}],
  p_fraud:[{n:'Defaut de paiement cartes de credit (XAI)',w:'terrain proche fraude, explicabilite'}],
  p_nlp:[{n:'CVproject, filtre de CV (NLP)',w:'extraction de competences par patterns spaCy, interface app'}],
  p_llm:[{n:'LLM Society (Veille Techno)',w:'simulation multi-agents, chaque agent un LLM avec sa personnalite'}],
  p_fgraph:[{n:'Detection de fraude AML sur graphe',w:'objectif CV: GraphSAGE/GAT et explicabilite GNN'}],
  p_trader:[{n:'Neuro-Graph Trader, sujet R&D (sujet.md)',w:'DGT, RL residuel PPO/SAC, NLP FinBERT, XAI, objectif CV'}],
}
